# Generated by Django 4.2.1 on 2023-05-15 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Aircompany name')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(choices=[('business', 'business'), ('economy', 'economy'), ('captain', 'captain'), ('pilot', 'pilot'), ('flight attendant', 'flight attendant')], max_length=50, verbose_name='Command type')),
                ('air_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='airlines.aircompany')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch')], max_length=50, verbose_name='Food type')),
            ],
        ),
        migrations.CreateModel(
            name='HotFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotfood', models.CharField(blank=True, max_length=10, verbose_name='Необходимо указать тип HB or HM')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotfoods', to='airlines.food')),
            ],
        ),
        migrations.CreateModel(
            name='Rotating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation', models.CharField(blank=True, choices=[('Rotation-1', 'Rotation-1'), ('Rotation-2', 'Rotation-2'), ('Rotation-3', 'Rotation-3'), ('Days 1-10', 'Days 1-10'), ('Days 11-20', 'Days 11-20'), ('Days 21-30', 'Days 21-30')], max_length=50, verbose_name='Rotation type')),
                ('special', models.TextField(blank=True, verbose_name='Спецпитание с номером указать здесь!!!')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotatings', to='airlines.command')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/')),
                ('hotfood', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='airlines.hotfood')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='rotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='airlines.rotating'),
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_company', models.ManyToManyField(to='airlines.aircompany')),
                ('command', models.ManyToManyField(to='airlines.command')),
                ('food', models.ManyToManyField(to='airlines.food')),
                ('hotfood', models.ManyToManyField(to='airlines.hotfood')),
                ('image', models.ManyToManyField(to='airlines.image')),
                ('rotating', models.ManyToManyField(to='airlines.rotating')),
            ],
        ),
    ]
