# Generated by Django 4.2.1 on 2023-05-10 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AirCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Aircompany name')),
            ],
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(choices=[('business', 'business'), ('economy', 'economy'), ('flight attendant', 'flight attendant'), ('pilot', 'pilot'), ('captain', 'captain')], max_length=50, verbose_name='Command type')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(choices=[('breakfast', 'breakfast'), ('lunch', 'lunch'), ('dinner', 'dinner')], max_length=50, verbose_name='Food type')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='airlines.command')),
            ],
        ),
        migrations.CreateModel(
            name='Rotating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotation', models.CharField(choices=[('Rotation-1', 'Rotation-1'), ('Rotation-2', 'Rotation-2'), ('Rotation-3', 'Rotation-3')], max_length=50, verbose_name='Rotation type')),
                ('air_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotatings', to='airlines.aircompany')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='airlines.food')),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_company', models.ManyToManyField(to='airlines.aircompany')),
                ('command', models.ManyToManyField(to='airlines.command')),
                ('food', models.ManyToManyField(to='airlines.food')),
                ('image', models.ManyToManyField(to='airlines.image')),
                ('rotating', models.ManyToManyField(to='airlines.rotating')),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='rotating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='airlines.rotating'),
        ),
    ]
